name: CI/CD Pipeline
run-name: Automatizar o processo de CI/CD para o projeto

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configura o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instala dependências
        run: npm install

      - name: Roda testes Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 30

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Configura o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Deploy para Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'autoprime-grupo9'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .